name: Release Automation

on:
  push:
    branches:
      - main # Replace with your release branch if different
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (adjust for your environment)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build project
        run: npm run build
      # Step 5: Generate a version tag
      - name: Generate version
        id: generate_version
        run: |
          VERSION=$(date +'%Y.%m.%d.%H%M%S')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        env:
          VERSION: ${{ env.VERSION }}
